### ISSUE TITLE
Missing image firmware

### ISSUE THREAD

**Issue by mtuxpe** [sipeed/RV-Debugger-BL702#13]
it looks like the repository is incomplete. I can't find for example the main.bin file

**Comment by taorye** [comment]
it's actually not released. But the latest firmware is located on `Actions`, you can find it there.

**Comment by taorye** [comment]
We have also provided firmware of usb2dualuart, you can take a look.

**Comment by pansila** [comment]
![image](https://github.com/sipeed/RV-Debugger-BL702/assets/5125601/417f6c67-e593-44b5-9ce1-5fe716bb5e5d)
