### ISSUE TITLE
usb2uartjtag固件，uart使用不了

### ISSUE THREAD

**Issue by xulinkun** [sipeed/RV-Debugger-BL702#14]
调试板为 rv-debugger-plus，目标机器是sipeed nano，编译出来发现jtag能用，但是uart无通信。起初怀疑硬件的问题，但对比烧录sdk example下的usb2uart用例，uart通信正常，所以认定是固件bug，请排查一下。

**Comment by luvletter2333** [comment]
把这一行注释掉，重新编译然后烧固件就行了，但是我还没测试jtag好不好使

https://github.com/sipeed/RV-Debugger-BL702/blob/cdc36a481b8d06be261e5094202ac9e313fa585c/firmware/app/usb2uartjtag/uart_interface.c#L74

这一行在 usb2dualuart下面是被注释掉了的

https://github.com/sipeed/RV-Debugger-BL702/blob/cdc36a481b8d06be261e5094202ac9e313fa585c/firmware/app/usb2dualuart/uart_interface.c#L56

小编也很好奇为什么

**Comment by richardclli** [comment]
Fixed了
https://github.com/sipeed/RV-Debugger-BL702/pull/19
